language: node_js
node_js:
- node
sudo: false
script:
- npm run test
- npm run coverage
- npm run build
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: 0fa8f40e2a194d3ea2c84f2886582642c1569be0328ebfed3ca814e78731ee65
deploy:
  provider: npm
  skip_cleanup: true
  email: stephen.austin@rovisys.com
  api_key:
    secure: zKY6VzElMFjtUZ3uTnqS+npPbDRj4knhToAXKGqIEp0084UbMELoxgFbSu5sXX+5JIsj+Bir+D1aHnoE7w48B/LsVFN4eO22yYW10FsqfxyNKvgjq11+w40JQkjEAiXnxDUsSZoiusAxXCzsn3WGcoZYK1MbYFX1qEfS8Bc1BkhrN/2cnw7ysgVGepvxGP06rXnB+js3vqYNqWAAPyJubU1ZKz7kP1fP6HnwFYPdZBr1KYzkMhWLE+UjRAl2cFaRGQ4uxvXRpnUJbdcERqDUJNZxvwEPnNuoF1vD0CpCdIoyGsMIuKBt5rsOixKNyPC/GEl/JadHdt4GRwq9MRKVU542qzRzXy0KJLhc4pon2jr8O6019wSuLS8Ekvdw9A5VAYHAjapR9gSij4ASYMHOYz7h5d6GnW7AzdaHtzJgQ1oz9eQycmOVfN6LUyJ1ssWdr9CFKLGLbFDJEdUv713GEiHrTZd4r0w3zuwJ+KnOiPrSW1btCadtIKgkbICgZ03T4GV4OT2WgUY4FM/d+gy/NfjoopNwv9uM/eqiV3UPErE9jUFuZWDvF/dEvttHewAy8i8510s5zgZKL+JhaRBe8HSkmOYujabuE/AR6tVf8pTvhcsagPJ+p6SnZiRUR+Q8YUaYYN/TWvElrWwubk2OYO9YC053aydd0QjByEzqebw=
  on:
    tags: true
    repo: RoviSys/react-pure-decorator
